name: flex_storefront
description: "Flex Storefront is an open-source mobile app that allows you to quickly create your own branded storefront for SAP Commerce Cloud."

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  auto_route: ^7.9.2
  badges: ^3.1.2
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  dio: ^5.4.1
  emarsys_sdk: ^2.3.3
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  firebase_remote_config: ^5.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_breadcrumb: ^1.0.1
  flutter_carousel_widget: ^2.2.0
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.2.1
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.1.0
  flutter_secure_storage: ^4.2.1
  form_builder_validators: ^9.1.0
  fresh_dio: ^0.4.1
  get_it: ^7.6.9
  html: ^0.15.4
  icons_plus: ^5.0.0
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  lottie: ^3.1.2
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  sheet: ^1.0.0
  shimmer: ^3.0.0
  widgetbook: ^3.7.1
  widgetbook_annotation: ^3.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
